<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Marks generated sample records so they can be removed without touching real data. */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('members', function (Blueprint $table) {
            $table->boolean('is_sample')->default(false)->after('is_verified')->comment('Generated by members:sample');
        });

        Schema::table('event_participants', function (Blueprint $table) {
            $table->boolean('is_sample')->default(false)->after('source')->comment('Generated by event-participants:sample');
        });

        Schema::table('member_requests', function (Blueprint $table) {
            $table->boolean('is_sample')->default(false)->after('handled_at')->comment('Generated by requests:sample');
        });
    }

    public function down(): void
    {
        Schema::table('members', function (Blueprint $table) {
            $table->dropColumn('is_sample');
        });

        Schema::table('event_participants', function (Blueprint $table) {
            $table->dropColumn('is_sample');
        });

        Schema::table('member_requests', function (Blueprint $table) {
            $table->dropColumn('is_sample');
        });
    }
};
