<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/** Marks generated sample records so they can be removed without touching real registrations. */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('young_members', function (Blueprint $table) {
            $table->boolean('is_sample')->default(false)->after('status')->comment('Generated by young-members:sample');
        });
    }

    public function down(): void
    {
        Schema::table('young_members', function (Blueprint $table) {
            $table->dropColumn('is_sample');
        });
    }
};
