#!/bin/bash
# Generates 03_migrate_ledger.sql: ~60 near-identical income/expense tables -> ledger_categories + income + expenses,
# and the wide budget tables -> budget_lines. Run: bash 03_generate_ledger.sh > 03_migrate_ledger.sql
M="mysql -u root"
mq() { $M -N -e "$1" | tr -d '\015'; }  # mysql.exe emits CRLF
L=pcg_ecm_legacy

# code|Label  (labels for codes whose meaning is not documented are kept close to the table name)
EXPENSE_LIST=(
"accomodation|Accommodation" "adverts|Advertising" "almanacexes|Almanac" "almanacex|Almanac (unlinked)" "appreciation|Appreciation"
"assesother|Other assessments" "assetexp|Asset expenses" "bankf|Bank charges" "brigade|Brigade" "cleaning|Cleaning" "communion|Communion"
"cservice|CService" "donations|Donations" "dues|Dues" "education|Education" "esr|ESR" "evangelism|Evangelism" "fuel|Fuel"
"funeral|Funeral donations" "generator|Generator" "harvestex|Harvest expenses" "imprest|Imprest" "invalid|Invalid fund"
"junior|Junior youth" "lighting|Lighting" "maintenance|Maintenance" "manse|Manse" "medication|Medication" "meetings|Meetings"
"mproject|Projects" "music|Music" "newasset|New assets" "newspaper|Newspaper" "office|Office" "oproject|Other projects"
"otherdo|Other donations" "otherexpayments|Other payments" "prate|Property rate" "printing|Printing" "refreshment|Refreshment"
"revivals|Revivals" "savings|Savings" "ssnit|SSNIT" "suppliers|Suppliers" "tax|Tax" "telecome|Telecom" "transport|Transport"
"utility|Utilities" "vehicle|Vehicle")
INCOME_LIST=(
"abume|Abume" "aged|Aged" "allnight|All-night service" "almanac|Almanac" "evening|Evening service" "harvest|Harvest"
"jerico|Jerico" "marriage|Marriage" "morningdevo|Morning devotion" "otherincome|Other income" "pgroup|Group programme"
"projecto|Project income")

echo "-- GENERATED by 03_generate_ledger.sh - do not edit by hand."
echo "USE pcg_ecm; SET NAMES utf8mb4; SET SESSION sql_mode='STRICT_TRANS_TABLES'; SET FOREIGN_KEY_CHECKS=0; START TRANSACTION;"

for pair in "${EXPENSE_LIST[@]}"; do echo "INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','${pair%%|*}','$(echo "${pair#*|}" | sed "s/'/''/g")');"; done
for pair in "${INCOME_LIST[@]}"; do echo "INSERT INTO ledger_categories (kind, code, name) VALUES ('income','${pair%%|*}','$(echo "${pair#*|}" | sed "s/'/''/g")');"; done

# valid date, else the entry timestamp
DATEX="IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date)"

for pair in "${EXPENSE_LIST[@]}"; do
  t=${pair%%|*}
  cols=$(mq "SELECT GROUP_CONCAT(column_name) FROM information_schema.columns WHERE table_schema='$L' AND table_name='$t'")
  has() { case ",$cols," in *",$1,"*) return 0;; *) return 1;; esac; }
  desc="NULLIF(TRIM(t.description),'')"; has description || desc="NULL"
  # optional legacy sub-labels are folded into the description so nothing is lost
  if has category;      then desc="NULLIF(CONCAT_WS(' - ', NULLIF(TRIM(t.category),''), $desc),'')"; fi
  if has assettype_id;  then desc="NULLIF(CONCAT_WS(' - ', (SELECT CONCAT('Asset type: ', a.name) FROM $L.assettypes a WHERE a.id=t.assettype_id), $desc),'')"; fi
  payee="NULL";   has client_id  && payee="IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL)"
  chq="NULL";     has chequeno   && chq="NULLIF(TRIM(t.chequeno),'')"
  pv="NULL";      has pvnumber   && pv="NULLIF(TRIM(t.pvnumber),'')"
  proj="NULL";    has projectname_id && proj="IF(t.projectname_id IN (SELECT id FROM projects), t.projectname_id, NULL)"
  usr="NULL";     has user_id    && usr="IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL)"
  lusr="NULL";    has user_id    && lusr="NULLIF(t.user_id,0)"
  echo "INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, $DATEX, t.amount, $desc, $payee, $chq, $pv, $proj, $usr, NULLIF(t.created,'0000-00-00 00:00:00'), '$t', t.id, $lusr
FROM $L.\`$t\` t JOIN ledger_categories c ON c.kind='expense' AND c.code='$t';"
done

for pair in "${INCOME_LIST[@]}";do
  t=${pair%%|*}
  cols=$(mq "SELECT GROUP_CONCAT(column_name) FROM information_schema.columns WHERE table_schema='$L' AND table_name='$t'")
  has() { case ",$cols," in *",$1,"*) return 0;; *) return 1;; esac; }
  desc="NULLIF(TRIM(t.description),'')"; has description || desc="NULL"
  if has groupname_id; then desc="NULLIF(CONCAT_WS(' - ', (SELECT CONCAT('Group: ', g.name) FROM $L.groupname g WHERE g.id=t.groupname_id), $desc),'')"; fi
  proj="NULL"; has projectname_id && proj="IF(t.projectname_id IN (SELECT id FROM projects), t.projectname_id, NULL)"
  echo "INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, $DATEX, t.amount, $desc, NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), $proj, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), '$t', t.id, NULLIF(t.user_id,0)
FROM $L.\`$t\` t JOIN ledger_categories c ON c.kind='income' AND c.code='$t';"
done

# wide budget tables -> one row per (date, item); zero amounts are dropped
unpivot() { # table direction excluded-cols-regex
  for c in $(mq "SELECT column_name FROM information_schema.columns WHERE table_schema='$L' AND table_name='$1' AND column_name NOT REGEXP '$3' ORDER BY ordinal_position"); do
    echo "INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), '$2', '$c', \`$c\`, '$1', id FROM $L.\`$1\` WHERE \`$c\` IS NOT NULL AND \`$c\` <> 0;"
  done
}
unpivot budgetinflow  inflow  '^(id|date|user_id|total|created)$'
unpivot budgetoutflow outflow '^(id|date|user_id|total|created)$'
for t in tithebudget budgetharvest budgetvto; do
  echo "INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', '$t', amount, '$t', id FROM $L.\`$t\` WHERE amount <> 0;"
done

echo "COMMIT; SET FOREIGN_KEY_CHECKS=1;"
