-- GENERATED by 03_generate_ledger.sh - do not edit by hand.
USE pcg_ecm; SET NAMES utf8mb4; SET SESSION sql_mode='STRICT_TRANS_TABLES'; SET FOREIGN_KEY_CHECKS=0; START TRANSACTION;
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','accomodation','Accommodation');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','adverts','Advertising');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','almanacexes','Almanac');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','almanacex','Almanac (unlinked)');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','appreciation','Appreciation');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','assesother','Other assessments');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','assetexp','Asset expenses');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','bankf','Bank charges');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','brigade','Brigade');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','cleaning','Cleaning');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','communion','Communion');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','cservice','CService');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','donations','Donations');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','dues','Dues');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','education','Education');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','esr','ESR');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','evangelism','Evangelism');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','fuel','Fuel');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','funeral','Funeral donations');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','generator','Generator');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','harvestex','Harvest expenses');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','imprest','Imprest');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','invalid','Invalid fund');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','junior','Junior youth');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','lighting','Lighting');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','maintenance','Maintenance');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','manse','Manse');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','medication','Medication');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','meetings','Meetings');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','mproject','Projects');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','music','Music');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','newasset','New assets');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','newspaper','Newspaper');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','office','Office');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','oproject','Other projects');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','otherdo','Other donations');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','otherexpayments','Other payments');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','prate','Property rate');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','printing','Printing');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','refreshment','Refreshment');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','revivals','Revivals');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','savings','Savings');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','ssnit','SSNIT');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','suppliers','Suppliers');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','tax','Tax');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','telecome','Telecom');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','transport','Transport');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','utility','Utilities');
INSERT INTO ledger_categories (kind, code, name) VALUES ('expense','vehicle','Vehicle');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','abume','Abume');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','aged','Aged');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','allnight','All-night service');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','almanac','Almanac');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','evening','Evening service');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','harvest','Harvest');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','jerico','Jerico');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','marriage','Marriage');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','morningdevo','Morning devotion');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','otherincome','Other income');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','pgroup','Group programme');
INSERT INTO ledger_categories (kind, code, name) VALUES ('income','projecto','Project income');
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'accomodation', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`accomodation` t JOIN ledger_categories c ON c.kind='expense' AND c.code='accomodation';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'adverts', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`adverts` t JOIN ledger_categories c ON c.kind='expense' AND c.code='adverts';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'almanacexes', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`almanacexes` t JOIN ledger_categories c ON c.kind='expense' AND c.code='almanacexes';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULL, NULL, NULL, NULL, NULL, NULLIF(t.created,'0000-00-00 00:00:00'), 'almanacex', t.id, NULL
FROM pcg_ecm_legacy.`almanacex` t JOIN ledger_categories c ON c.kind='expense' AND c.code='almanacex';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'appreciation', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`appreciation` t JOIN ledger_categories c ON c.kind='expense' AND c.code='appreciation';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'assesother', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`assesother` t JOIN ledger_categories c ON c.kind='expense' AND c.code='assesother';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(CONCAT_WS(' - ', (SELECT CONCAT('Asset type: ', a.name) FROM pcg_ecm_legacy.assettypes a WHERE a.id=t.assettype_id), NULLIF(TRIM(t.description),'')),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'assetexp', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`assetexp` t JOIN ledger_categories c ON c.kind='expense' AND c.code='assetexp';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'bankf', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`bankf` t JOIN ledger_categories c ON c.kind='expense' AND c.code='bankf';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'brigade', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`brigade` t JOIN ledger_categories c ON c.kind='expense' AND c.code='brigade';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'cleaning', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`cleaning` t JOIN ledger_categories c ON c.kind='expense' AND c.code='cleaning';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'communion', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`communion` t JOIN ledger_categories c ON c.kind='expense' AND c.code='communion';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'cservice', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`cservice` t JOIN ledger_categories c ON c.kind='expense' AND c.code='cservice';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'donations', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`donations` t JOIN ledger_categories c ON c.kind='expense' AND c.code='donations';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'dues', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`dues` t JOIN ledger_categories c ON c.kind='expense' AND c.code='dues';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'education', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`education` t JOIN ledger_categories c ON c.kind='expense' AND c.code='education';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'esr', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`esr` t JOIN ledger_categories c ON c.kind='expense' AND c.code='esr';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'evangelism', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`evangelism` t JOIN ledger_categories c ON c.kind='expense' AND c.code='evangelism';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'fuel', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`fuel` t JOIN ledger_categories c ON c.kind='expense' AND c.code='fuel';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'funeral', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`funeral` t JOIN ledger_categories c ON c.kind='expense' AND c.code='funeral';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'generator', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`generator` t JOIN ledger_categories c ON c.kind='expense' AND c.code='generator';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'harvestex', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`harvestex` t JOIN ledger_categories c ON c.kind='expense' AND c.code='harvestex';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'imprest', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`imprest` t JOIN ledger_categories c ON c.kind='expense' AND c.code='imprest';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'invalid', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`invalid` t JOIN ledger_categories c ON c.kind='expense' AND c.code='invalid';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'junior', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`junior` t JOIN ledger_categories c ON c.kind='expense' AND c.code='junior';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'lighting', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`lighting` t JOIN ledger_categories c ON c.kind='expense' AND c.code='lighting';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'maintenance', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`maintenance` t JOIN ledger_categories c ON c.kind='expense' AND c.code='maintenance';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'manse', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`manse` t JOIN ledger_categories c ON c.kind='expense' AND c.code='manse';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'medication', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`medication` t JOIN ledger_categories c ON c.kind='expense' AND c.code='medication';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'meetings', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`meetings` t JOIN ledger_categories c ON c.kind='expense' AND c.code='meetings';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), IF(t.projectname_id IN (SELECT id FROM projects), t.projectname_id, NULL), IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'mproject', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`mproject` t JOIN ledger_categories c ON c.kind='expense' AND c.code='mproject';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'music', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`music` t JOIN ledger_categories c ON c.kind='expense' AND c.code='music';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'newasset', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`newasset` t JOIN ledger_categories c ON c.kind='expense' AND c.code='newasset';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'newspaper', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`newspaper` t JOIN ledger_categories c ON c.kind='expense' AND c.code='newspaper';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'office', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`office` t JOIN ledger_categories c ON c.kind='expense' AND c.code='office';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'oproject', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`oproject` t JOIN ledger_categories c ON c.kind='expense' AND c.code='oproject';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'otherdo', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`otherdo` t JOIN ledger_categories c ON c.kind='expense' AND c.code='otherdo';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'otherexpayments', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`otherexpayments` t JOIN ledger_categories c ON c.kind='expense' AND c.code='otherexpayments';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'prate', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`prate` t JOIN ledger_categories c ON c.kind='expense' AND c.code='prate';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'printing', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`printing` t JOIN ledger_categories c ON c.kind='expense' AND c.code='printing';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'refreshment', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`refreshment` t JOIN ledger_categories c ON c.kind='expense' AND c.code='refreshment';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'revivals', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`revivals` t JOIN ledger_categories c ON c.kind='expense' AND c.code='revivals';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'savings', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`savings` t JOIN ledger_categories c ON c.kind='expense' AND c.code='savings';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULL, IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'ssnit', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`ssnit` t JOIN ledger_categories c ON c.kind='expense' AND c.code='ssnit';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULL, NULL, NULL, NULL, NULL, NULLIF(t.created,'0000-00-00 00:00:00'), 'suppliers', t.id, NULL
FROM pcg_ecm_legacy.`suppliers` t JOIN ledger_categories c ON c.kind='expense' AND c.code='suppliers';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULL, IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'tax', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`tax` t JOIN ledger_categories c ON c.kind='expense' AND c.code='tax';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(CONCAT_WS(' - ', NULLIF(TRIM(t.category),''), NULLIF(TRIM(t.description),'')),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'telecome', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`telecome` t JOIN ledger_categories c ON c.kind='expense' AND c.code='telecome';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'transport', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`transport` t JOIN ledger_categories c ON c.kind='expense' AND c.code='transport';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(CONCAT_WS(' - ', NULLIF(TRIM(t.category),''), NULLIF(TRIM(t.description),'')),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'utility', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`utility` t JOIN ledger_categories c ON c.kind='expense' AND c.code='utility';
INSERT INTO expenses (category_id, spent_on, amount, description, payee_id, cheque_no, pv_number, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), IF(t.client_id IN (SELECT id FROM payees), t.client_id, NULL), NULLIF(TRIM(t.chequeno),''), NULLIF(TRIM(t.pvnumber),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'vehicle', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`vehicle` t JOIN ledger_categories c ON c.kind='expense' AND c.code='vehicle';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'abume', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`abume` t JOIN ledger_categories c ON c.kind='income' AND c.code='abume';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'aged', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`aged` t JOIN ledger_categories c ON c.kind='income' AND c.code='aged';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'allnight', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`allnight` t JOIN ledger_categories c ON c.kind='income' AND c.code='allnight';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'almanac', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`almanac` t JOIN ledger_categories c ON c.kind='income' AND c.code='almanac';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'evening', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`evening` t JOIN ledger_categories c ON c.kind='income' AND c.code='evening';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'harvest', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`harvest` t JOIN ledger_categories c ON c.kind='income' AND c.code='harvest';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'jerico', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`jerico` t JOIN ledger_categories c ON c.kind='income' AND c.code='jerico';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'marriage', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`marriage` t JOIN ledger_categories c ON c.kind='income' AND c.code='marriage';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'morningdevo', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`morningdevo` t JOIN ledger_categories c ON c.kind='income' AND c.code='morningdevo';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'otherincome', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`otherincome` t JOIN ledger_categories c ON c.kind='income' AND c.code='otherincome';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(CONCAT_WS(' - ', (SELECT CONCAT('Group: ', g.name) FROM pcg_ecm_legacy.groupname g WHERE g.id=t.groupname_id), NULLIF(TRIM(t.description),'')),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), NULL, IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'pgroup', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`pgroup` t JOIN ledger_categories c ON c.kind='income' AND c.code='pgroup';
INSERT INTO income (category_id, received_on, amount, description, paid_by, invoice_no, project_id, recorded_by, created_at, legacy_table, legacy_id, legacy_user_id)
SELECT c.id, IF(t.date IS NULL OR t.date < '2000-01-01' OR t.date > CURDATE(), DATE(t.created), t.date), t.amount, NULLIF(TRIM(t.description),''), NULLIF(TRIM(t.paidby),''), NULLIF(TRIM(t.invoicenum),''), IF(t.projectname_id IN (SELECT id FROM projects), t.projectname_id, NULL), IF(t.user_id IN (SELECT id FROM users), t.user_id, NULL), NULLIF(t.created,'0000-00-00 00:00:00'), 'projecto', t.id, NULLIF(t.user_id,0)
FROM pcg_ecm_legacy.`projecto` t JOIN ledger_categories c ON c.kind='income' AND c.code='projecto';
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'tithe', `tithe`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `tithe` IS NOT NULL AND `tithe` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'vto', `vto`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `vto` IS NOT NULL AND `vto` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'harvestlevy', `harvestlevy`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `harvestlevy` IS NOT NULL AND `harvestlevy` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'groupprogramme', `groupprogramme`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `groupprogramme` IS NOT NULL AND `groupprogramme` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'almanac', `almanac`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `almanac` IS NOT NULL AND `almanac` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'marriage', `marriage`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `marriage` IS NOT NULL AND `marriage` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'mainharvest', `mainharvest`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `mainharvest` IS NOT NULL AND `mainharvest` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'offertory', `offertory`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `offertory` IS NOT NULL AND `offertory` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'allnight', `allnight`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `allnight` IS NOT NULL AND `allnight` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'morningd', `morningd`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `morningd` IS NOT NULL AND `morningd` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'preachingpost', `preachingpost`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `preachingpost` IS NOT NULL AND `preachingpost` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'fridayev', `fridayev`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `fridayev` IS NOT NULL AND `fridayev` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'offinvalid', `offinvalid`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `offinvalid` IS NOT NULL AND `offinvalid` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'otherincome', `otherincome`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `otherincome` IS NOT NULL AND `otherincome` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'otherchrhacti', `otherchrhacti`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `otherchrhacti` IS NOT NULL AND `otherchrhacti` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'projectoff', `projectoff`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `projectoff` IS NOT NULL AND `projectoff` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'welfare', `welfare`, 'budgetinflow', id FROM pcg_ecm_legacy.`budgetinflow` WHERE `welfare` IS NOT NULL AND `welfare` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'assesment', `assesment`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `assesment` IS NOT NULL AND `assesment` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'otherassesment', `otherassesment`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `otherassesment` IS NOT NULL AND `otherassesment` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'salary', `salary`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `salary` IS NOT NULL AND `salary` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'allowance', `allowance`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `allowance` IS NOT NULL AND `allowance` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'communion', `communion`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `communion` IS NOT NULL AND `communion` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'jy', `jy`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `jy` IS NOT NULL AND `jy` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'childrens', `childrens`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `childrens` IS NOT NULL AND `childrens` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'brigade', `brigade`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `brigade` IS NOT NULL AND `brigade` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'evangelism', `evangelism`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `evangelism` IS NOT NULL AND `evangelism` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'invalidd', `invalidd`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `invalidd` IS NOT NULL AND `invalidd` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'otherdonation', `otherdonation`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `otherdonation` IS NOT NULL AND `otherdonation` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'funeraldonation', `funeraldonation`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `funeraldonation` IS NOT NULL AND `funeraldonation` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'harvestexp', `harvestexp`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `harvestexp` IS NOT NULL AND `harvestexp` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'dues', `dues`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `dues` IS NOT NULL AND `dues` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'education', `education`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `education` IS NOT NULL AND `education` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'ecsr', `ecsr`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `ecsr` IS NOT NULL AND `ecsr` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'medication', `medication`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `medication` IS NOT NULL AND `medication` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'printing', `printing`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `printing` IS NOT NULL AND `printing` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'newspaper', `newspaper`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `newspaper` IS NOT NULL AND `newspaper` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'officecomputer', `officecomputer`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `officecomputer` IS NOT NULL AND `officecomputer` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'cleaning', `cleaning`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `cleaning` IS NOT NULL AND `cleaning` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'advertising', `advertising`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `advertising` IS NOT NULL AND `advertising` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'refreshment', `refreshment`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `refreshment` IS NOT NULL AND `refreshment` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'bcharges', `bcharges`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `bcharges` IS NOT NULL AND `bcharges` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'generator', `generator`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `generator` IS NOT NULL AND `generator` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'project', `project`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `project` IS NOT NULL AND `project` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'officequip', `officequip`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `officequip` IS NOT NULL AND `officequip` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'furniture', `furniture`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `furniture` IS NOT NULL AND `furniture` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'music', `music`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `music` IS NOT NULL AND `music` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'accomodation', `accomodation`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `accomodation` IS NOT NULL AND `accomodation` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'telecom', `telecom`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `telecom` IS NOT NULL AND `telecom` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'utilities', `utilities`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `utilities` IS NOT NULL AND `utilities` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'conference', `conference`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `conference` IS NOT NULL AND `conference` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'transport', `transport`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `transport` IS NOT NULL AND `transport` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'propertyrate', `propertyrate`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `propertyrate` IS NOT NULL AND `propertyrate` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'outflow', 'appreciation', `appreciation`, 'budgetoutflow', id FROM pcg_ecm_legacy.`budgetoutflow` WHERE `appreciation` IS NOT NULL AND `appreciation` <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'tithebudget', amount, 'tithebudget', id FROM pcg_ecm_legacy.`tithebudget` WHERE amount <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'budgetharvest', amount, 'budgetharvest', id FROM pcg_ecm_legacy.`budgetharvest` WHERE amount <> 0;
INSERT INTO budget_lines (budget_date, direction, item_code, amount, legacy_table, legacy_id)
SELECT NULLIF(date,'0000-00-00'), 'inflow', 'budgetvto', amount, 'budgetvto', id FROM pcg_ecm_legacy.`budgetvto` WHERE amount <> 0;
COMMIT; SET FOREIGN_KEY_CHECKS=1;
